package aws

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/aws/aws-sdk-go-v2/config"
	"github.com/firetiger-oss/storage/secret"
)

// Parses: arn:PARTITION:secretsmanager:REGION:ACCOUNT[:secret:NAME[-SUFFIX][:STAGE]]
// Group 1: manager ID (arn:PARTITION:secretsmanager:REGION:ACCOUNT)
// Group 2: secret name with suffix and stage stripped
var secretManagerARN = regexp.MustCompile(`^(arn:[^:]+:secretsmanager:[^:]+:\d{12})(?::secret:(.*?)(?:-[A-Za-z0-9]{6})?(?::[A-Z]+)?)?$`)

type registry struct{}

func init() {
	secret.Register("arn:", &registry{})
}

func (r *registry) LoadManager(ctx context.Context, identifier string) (secret.Manager, error) {
	managerID, _, _, err := r.ParseSecret(identifier)
	if err != nil {
		return nil, err
	}

	_, region, _ := strings.Cut(managerID, ":secretsmanager:")
	region, _, _ = strings.Cut(region, ":")

	cfg, err := config.LoadDefaultConfig(ctx, config.WithRegion(region))
	if err != nil {
		return nil, fmt.Errorf("load AWS config: %w", err)
	}

	return NewManagerFromConfig(cfg), nil
}

// ParseSecret parses an AWS Secrets Manager ARN.
// Format: arn:PARTITION:secretsmanager:REGION:ACCOUNT[:secret:NAME[-SUFFIX][:STAGE]]
// Where SUFFIX is exactly 6 alphanumeric characters auto-generated by AWS.
func (r *registry) ParseSecret(identifier string) (managerID, secretName, version string, err error) {
	m := secretManagerARN.FindStringSubmatch(identifier)
	if m == nil {
		return "", "", "", fmt.Errorf("invalid AWS Secrets Manager ARN: %q", identifier)
	}
	return m[1], m[2], "", nil
}
